### PR TITLE
Better events default

### PR DESCRIPTION
**Pull request by refractalize**
The current default only saves the file when you exit insert mode. But if you do any edits that don't involve insert mode, such as `dd` or `p` then no auto save is triggered.

Add `TextChanged` as a default event which triggers events for non-insert-mode edits.

### CODE REVIEW

**Comment by refractalize** [comment]
I wasn't sure if I need to update `default_event` [here](https://github.com/refractalize/AutoSave.nvim/blob/86adb4ef60f4d07737d3c724c123da6ccef22511/lua/autosave/modules/autocmds.lua#L7). It looks like we're assuming there's only one event [here](https://github.com/refractalize/AutoSave.nvim/blob/86adb4ef60f4d07737d3c724c123da6ccef22511/lua/autosave/modules/autocmds.lua#L137)... Thought I'd clarify before making the change.

**Comment by Pocco81** [comment]
Now with the debounce feature it'd be great to add TextChanged as the default, so feel free to add that commit to this PR before I merge it. About the lines you mentioned, I know it looks like there is an issue with [this line](https://github.com/Pocco81/AutoSave.nvim/blob/main/lua/autosave/modules/autocmds.lua#L179) for only picking the first event, but trust me, it's okay.

It's like that because `doautoall` executes the commands of an `augroup` which match an event (not that the event is being executed, just that the event matches), this means that I can, for example, excute the commands with a `VimEnter` in an `augroup` on another event that has nothing to do with it.

Why did I implement it like that? Because I needed to iterate through all the buffers and the first three methods I tried had issues (bufdo, a custom BufDo and a very old method of grabbing the list of buffers and iterating with a for).

The current solution, which is a recursive implementation, solves all of those problems. In order of execution it: parses the events given (the default is passed if the table or var are empty), checks if x var doesn't exist (which shouldn't at this point), if it doesn't, instantiates it and executea the events of the autocommand recursively and unlet it afterwards. Now that the var exists, it should save the buffer `doautoall` is over at the moment. When that finishes it goes back to the beginning and unlets the var as I just said.

**Comment by refractalize** [comment]
I've added `TextChanged` to default_events, changed it to an array and put the the fallback behaviour into an `events()` function.

If I understand you correctly it doesn't matter which event we pass to the write_all_buffers code, as long as it's one of the events originally used to set up the autocmds then it'll work. I think what I have here should do the trick but let me know if you need further improvements.

**Comment by Pocco81** [comment]
I appreciate the fact you updated the doc and README as well. Thanks! no further improvements are needed for this PR.

**Pull request merged**
